print("Program to output average in 5 subject: ")
a = float(input("Enter marks of First subject: "))
b = float(input("Enter marks of Second subject: "))
c = float(input("Enter marks of Third subject: "))
d = float(input("Enter marks of Fourth subject: "))
e = float(input("Enter marks of Fifth subject: "))
avg = ((a+b+c+d+e)/5)
print("Average number of the Five subjects is : ",avg)