Psi=int(input("Enter the principle amount for simple interest: "))
rsi=int(input("Enter the rate for simple interest: "))
tsi=int(input("Enter the time for simple interest: "))
Pci=int(input("Enter the principle amount for Compound interest: "))
rci=int(input("Enter the rate for Compound interest: "))
tci=int(input("Enter the time for Compound interest: "))
SI=((Psi*rsi*tsi)/100)
CI=(Pci*(1+(rci/100)**tci))
print("The Simple interest is: ",SI)
print("The Compound interest is: ",CI)

